CREATE TABLE `02773_research`.cegek (
    id SERIAL PRIMARY KEY,
    nev VARCHAR(255) NOT NULL,
    nyilvantartasi_szam VARCHAR(50) UNIQUE NOT NULL,
    adoszam VARCHAR(50) NOT NULL,
    ksh_szam VARCHAR(50),
    szekhely VARCHAR(255),
    szekhely_varos VARCHAR(255),
    szekhely_iranyitoszam INTEGER NOT NULL
);

CREATE TABLE `02773_research`.beszamolok (
    id SERIAL PRIMARY KEY,
    ceg_id INT REFERENCES `02773_research`.cegek(id),
    uzleti_ev_kezdete DATE NOT NULL,
    uzleti_ev_vege DATE NOT NULL,
    et_ev INT NOT NULL, -- pl. 2016
    penznem VARCHAR(10) DEFAULT 'HUF',
    penzegyseg VARCHAR(20) DEFAULT 'ezer',
    atlagos_letszam INT,
    elfogadas_idopontja DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_ceg_ev UNIQUE (ceg_id, et_ev)
);

-- 1. Ürítsük ki a táblát a duplikációk eltávolításához
TRUNCATE TABLE `02773_research`.beszamolo_adatok;
-- 2. Tegyünk egy egyedi (UNIQUE) megszorítást a beszamolo_id oszlopra
ALTER TABLE `02773_research`.beszamolo_adatok
ADD CONSTRAINT unique_beszamolo_id UNIQUE (beszamolo_id);
CREATE TABLE `02773_research`.beszamolo_adatok (
    id SERIAL PRIMARY KEY,
    beszamolo_id INT REFERENCES `02773_research`.beszamolok(id) ON DELETE CASCADE,

    -- ==========================================
    -- ESZKÖZÖK (AKTÍVÁK)
    -- ==========================================
    eszkozok_osszesen NUMERIC(15, 2),
    a_befektetett_eszkozok NUMERIC(15, 2),
    a_i_immaterialis_javak NUMERIC(15, 2),
    a_i_1_alapitas_atszervezes_aktivalt_erteke NUMERIC(15, 2),
    a_i_2_kiserleti_fejlesztes_aktivalt_erteke NUMERIC(15, 2),
    a_i_3_vagyoni_erteku_jogok NUMERIC(15, 2),
    a_i_4_szellemi_termekek NUMERIC(15, 2),
    a_i_5_uzleti_vagy_cegertek NUMERIC(15, 2),
    a_i_6_immaterialis_javakra_adott_elolegek NUMERIC(15, 2),
    a_i_7_immaterialis_javak_ertekhelyesbitese NUMERIC(15, 2),
    a_ii_targyi_eszkozok NUMERIC(15, 2),
    a_ii_1_ingatlanok_es_a_kapcsolodo_vagyoni_erteku_jogok NUMERIC(15, 2),
    a_ii_2_muszaki_berendezesek_gepek_jarmuvek NUMERIC(15, 2),
    a_ii_3_egyeb_berendezesek_felszerelesek_jarmuvek NUMERIC(15, 2),
    a_ii_4_tenyeszallatok NUMERIC(15, 2),
    a_ii_5_beruhazasok_felujitasok NUMERIC(15, 2),
    a_ii_6_beruhazasokra_adott_elolegek NUMERIC(15, 2),
    a_ii_7_targyi_eszkozok_ertekhelyesbitese NUMERIC(15, 2),
    a_iii_befektetett_penzugyi_eszkozok NUMERIC(15, 2),
    a_iii_1_tartos_reszesedes_kapcsolt_vallalkozasban NUMERIC(15, 2),
    a_iii_2_tartosan_adott_kolcson_kapcsolt_vallalkozasban NUMERIC(15, 2),
    a_iii_3_tartos_jelentos_tulajdoni_reszesedes NUMERIC(15, 2),
    a_iii_4_tartosan_adott_kolcson_jelentos_tul_viszonyban NUMERIC(15, 2),
    a_iii_5_egyeb_tartos_reszesedes NUMERIC(15, 2),
    a_iii_6_tartosan_adott_kolcson_egyeb_reszesedesi_viszonyban NUMERIC(15, 2),
    a_iii_7_egyeb_tartosan_adott_kolcson NUMERIC(15, 2),
    a_iii_8_tartos_hitelviszonyt_megtestesito_ertekpapir NUMERIC(15, 2),
    a_iii_9_befektetett_penzugyi_eszkozok_ertekhelyesbitese NUMERIC(15, 2),
    a_iii_10_befektetett_penzugyi_eszkozok_ertekelesi_kulonbozete NUMERIC(15, 2),
    a_iv_halasztott_adokoveteles NUMERIC(15, 2), -- Későbbi években megjelenő sor

    b_forgoeszkozok NUMERIC(15, 2),
    b_i_keszletek NUMERIC(15, 2),
    b_i_1_anyagok NUMERIC(15, 2),
    b_i_2_befejezetlen_termeles_es_felkesz_termekek NUMERIC(15, 2),
    b_i_3_novendek_hizo_es_egyeb_allatok NUMERIC(15, 2),
    b_i_4_kesztermekek NUMERIC(15, 2),
    b_i_5_aruk NUMERIC(15, 2),
    b_i_6_keszletekre_adott_elolegek NUMERIC(15, 2),
    b_ii_kovetelesek NUMERIC(15, 2),
    b_ii_1_kovetelesek_aruszallitasbol_szolgaltatasbol_vevok NUMERIC(15, 2),
    b_ii_2_kovetelesek_kapcsolt_vallalkozassal_szemben NUMERIC(15, 2),
    b_ii_3_kovetelesek_jelentos_tulajdoni_reszesedesi_viszonyban NUMERIC(15, 2),
    b_ii_4_kovetelesek_egyeb_reszesedesi_viszonyban NUMERIC(15, 2),
    b_ii_5_valtokovetelesek NUMERIC(15, 2),
    b_ii_6_egyeb_kovetelesek NUMERIC(15, 2),
    b_ii_7_kovetelesek_ertekelesi_kulonbozete NUMERIC(15, 2),
    b_ii_8_szarmazekos_ugyletek_pozitiv_ertekelesi_kulonbozete NUMERIC(15, 2),
    b_iii_ertekpapirok NUMERIC(15, 2),
    b_iii_1_reszesedes_kapcsolt_vallalkozasban NUMERIC(15, 2),
    b_iii_2_jelentos_tulajdoni_reszesedes NUMERIC(15, 2),
    b_iii_3_egyeb_reszesedes NUMERIC(15, 2),
    b_iii_4_sajat_reszvenyek_sajat_uzletreszek NUMERIC(15, 2),
    b_iii_5_forgatasi_celu_hitelviszonyt_megtestesito_ertekpapirok NUMERIC(15, 2),
    b_iii_6_ertekpapirok_ertekelesi_kulonbozete NUMERIC(15, 2),
    b_iv_penzeszkozok NUMERIC(15, 2),
    b_iv_1_penztar_csekkek NUMERIC(15, 2),
    b_iv_2_bankbetetek NUMERIC(15, 2),

    c_aktiv_idobeli_elhatarolasok NUMERIC(15, 2),
    c_1_bevetelek_aktiv_idobeli_elhatarolasa NUMERIC(15, 2),
    c_2_koltsgek_forditasok_aktiv_idobeli_elhatarolasa NUMERIC(15, 2),
    c_3_halasztott_raforditasok NUMERIC(15, 2),

    -- ==========================================
    -- FORRÁSOK (PASSZÍVÁK)
    -- ==========================================
    forrasok_osszesen NUMERIC(15, 2),
    d_sajat_toke NUMERIC(15, 2),
    d_i_jegyzett_toke NUMERIC(15, 2),
    d_i_ebbol_visszavasarolt_tulajdoni_reszesedes NUMERIC(15, 2),
    d_ii_jegyzett_de_meg_be_nem_fizetett_toke NUMERIC(15, 2),
    d_iii_toketartalek NUMERIC(15, 2),
    d_iv_eredmenytartalek NUMERIC(15, 2),
    d_v_lekotott_tartalek NUMERIC(15, 2),
    d_vi_ertekelesi_tartalek NUMERIC(15, 2),
    d_vi_1_ertekhelyesbites_ertekelesi_tartaleka NUMERIC(15, 2),
    d_vi_2_valos_ertekeles_ertekelesi_tartaleka NUMERIC(15, 2),
    d_vii_adozott_eredmeny NUMERIC(15, 2),

    e_celtartalekok NUMERIC(15, 2),
    e_1_celtartalek_a_varhato_kotelezettsegekre NUMERIC(15, 2),
    e_2_celtartalek_a_jovobeni_koltsegekre NUMERIC(15, 2),
    e_3_egyeb_celtartalek NUMERIC(15, 2),

    f_kotelezettsegek NUMERIC(15, 2),
    f_i_hatrasorolt_kotelezettsegek NUMERIC(15, 2),
    f_i_1_hatrasorolt_kotelezettsegek_kapcsolt_vinnel NUMERIC(15, 2),
    f_i_2_hatrasorolt_kotelezettsegek_jelentos_tul_viszonyban NUMERIC(15, 2),
    f_i_3_hatrasorolt_kotelezettsegek_egyeb_reszesedesi_viszonyban NUMERIC(15, 2),
    f_i_4_hatrasorolt_kotelezettsegek_egyeb_gazdalkodoval NUMERIC(15, 2),
    f_ii_hosszu_lejaratu_kotelezettsegek NUMERIC(15, 2),
    f_ii_1_hosszu_lejaratra_kapott_kolcsonok NUMERIC(15, 2),
    f_ii_2_atvaltoztathato_es_atvaltozo_kotvenyek NUMERIC(15, 2),
    f_ii_3_tartozasok_kotvenykibocsatasbol NUMERIC(15, 2),
    f_ii_4_beruhazasi_es_fejlesztesi_hitelek NUMERIC(15, 2),
    f_ii_5_egyeb_hosszu_lejaratu_hitelek NUMERIC(15, 2),
    f_ii_6_tartos_kotelezettsegek_kapcsolt_vinnel NUMERIC(15, 2),
    f_ii_7_tartos_kotelezettsegek_jelentos_tul_viszonyban NUMERIC(15, 2),
    f_ii_8_tartos_kotelezettsegek_egyeb_reszesedesi_viszonyban NUMERIC(15, 2),
    f_ii_9_egyeb_hosszu_lejaratu_kotelezettsegek NUMERIC(15, 2),
    f_ii_10_halasztott_adokotelezettseg NUMERIC(15, 2),
    f_iii_rovid_lejaratu_kotelezettsegek NUMERIC(15, 2),
    f_iii_1_rovid_lejaratu_kolcsonok NUMERIC(15, 2),
    f_iii_1_ebbol_az_atvaltoztathato_kotvenyek NUMERIC(15, 2),
    f_iii_2_rovid_lejaratu_hitelek NUMERIC(15, 2),
    f_iii_3_vevoktol_kapott_elolegek NUMERIC(15, 2),
    f_iii_4_kotelezettsegek_aruszallitasbol_szolgal_szallitok NUMERIC(15, 2),
    f_iii_5_valtotartozasok NUMERIC(15, 2),
    f_iii_6_rovid_lejaratu_kotelezettsegek_kapcsolt_vinnel NUMERIC(15, 2),
    f_iii_7_rovid_lejaratu_kotelezettsegek_jelentos_tul_viszonyban NUMERIC(15, 2),
    f_iii_8_rovid_lejaratu_kotelezettsegek_egyeb_reszesedesi NUMERIC(15, 2),
    f_iii_9_egyeb_rovid_lejaratu_kotelezettsegek NUMERIC(15, 2),
    f_iii_10_kotelezettsegek_ertekelesi_kulonbozete NUMERIC(15, 2),
    f_iii_11_szarmazekos_ugyletek_negativ_ertekelesi_kulonbozete NUMERIC(15, 2),

    g_passziv_idobeli_elhatarolasok NUMERIC(15, 2),
    g_1_bevetelek_passziv_idobeli_elhatarolasa NUMERIC(15, 2),
    g_2_koltsgek_raforditasok_passziv_idobeli_elhatarolasa NUMERIC(15, 2),
    g_3_halasztott_bevetelek NUMERIC(15, 2),

    -- ==========================================
    -- EREDMÉNYKIMUTATÁS (Összköltség eljárás)
    -- ==========================================
    ek_01_belfoldi_ertekesites_netto_arbevetele NUMERIC(15, 2),
    ek_02_exportertekesites_netto_arbevetele NUMERIC(15, 2),
    ek_i_ertekesites_netto_arbevetele NUMERIC(15, 2),
    ek_03_sajat_termelesu_keszletek_allomanyvaltozasa NUMERIC(15, 2),
    ek_04_sajat_elallitasi_eszkozok_aktivalt_erteke NUMERIC(15, 2),
    ek_ii_aktivalt_sajat_teljesitmenyek_erteke NUMERIC(15, 2),
    ek_iii_egyeb_bevetelek NUMERIC(15, 2),
    ek_iii_ebbol_visszairt_ertekvesztes NUMERIC(15, 2),
    ek_05_anyagkoltseg NUMERIC(15, 2),
    ek_06_igenybe_vett_szolgaltatasok_erteke NUMERIC(15, 2),
    ek_07_egyeb_szolgaltatasok_erteke NUMERIC(15, 2),
    ek_08_eladott_aruk_beszerzesi_erteke NUMERIC(15, 2),
    ek_09_eladott_kozvetitett_szolgaltatasok_erteke NUMERIC(15, 2),
    ek_iv_anyagjellegu_raforditasok NUMERIC(15, 2),
    ek_10_berkoltseg NUMERIC(15, 2),
    ek_11_szemelyi_jellegu_egyeb_kifizetesek NUMERIC(15, 2),
    ek_12_berjarulekok NUMERIC(15, 2),
    ek_v_szemelyi_jellegu_raforditasok NUMERIC(15, 2),
    ek_vi_ertekcsokkenesi_leiras NUMERIC(15, 2),
    ek_vii_egyeb_raforditasok NUMERIC(15, 2),
    ek_vii_ebbol_ertekvesztes NUMERIC(15, 2),
    ek_a_uzemi_uzleti_tevekenyseg_eredmenye NUMERIC(15, 2),
    ek_13_kapott_jaro_osztalek_es_reszesedes NUMERIC(15, 2),
    ek_13_ebbol_kapcsolt_viallatkozastol_kapott NUMERIC(15, 2),
    ek_14_reszesedesekbol_szarmazo_bevetelek_arfolyamnyeresek NUMERIC(15, 2),
    ek_14_ebbol_kapcsolt_viallatkozastol_kapott NUMERIC(15, 2),
    ek_15_befektetett_penzugyi_eszkozokbol_szarmazo_bevetelek NUMERIC(15, 2),
    ek_15_ebbol_kapcsolt_viallatkozastol_kapott NUMERIC(15, 2),
    ek_16_egyeb_kapott_jaro_kamatok_es_kamatjellegu_bevetelek NUMERIC(15, 2),
    ek_16_ebbol_kapcsolt_viallatkozastol_kapott NUMERIC(15, 2),
    ek_17_penzugyi_muveletek_egyeb_bevetelek NUMERIC(15, 2),
    ek_17_ebbol_ertekelesi_kulonbozet NUMERIC(15, 2),
    ek_viii_penzugyi_muveletek_bevetelek NUMERIC(15, 2),
    ek_18_reszesedesekbol_szarmazo_raforditasok_arfolyamveszteségek NUMERIC(15, 2),
    ek_18_ebbol_kapcsolt_vallalkozasnak_adott NUMERIC(15, 2),
    ek_19_befektetett_penzugyi_eszkozok_raforditasai NUMERIC(15, 2),
    ek_19_ebbol_kapcsolt_vallalkozasnak_adott NUMERIC(15, 2),
    ek_20_fizetendo_kamatok_es_kamatjellegu_raforditasok NUMERIC(15, 2),
    ek_20_ebbol_kapcsolt_vallalkozasnak_adott NUMERIC(15, 2),
    ek_21_reszesedesek_ertekpapirok_bankbetetek_ertekvesztese NUMERIC(15, 2),
    ek_22_penzugyi_muveletek_egyeb_raforditasai NUMERIC(15, 2),
    ek_22_ebbol_ertekelesi_kulonbozet NUMERIC(15, 2),
    ek_ix_penzugyi_muveletek_raforditasai NUMERIC(15, 2),
    ek_b_penzugyi_muveletek_eredmenye NUMERIC(15, 2),
    ek_c_adozas_elotti_eredmeny NUMERIC(15, 2),
    ek_x_adofizetesi_kotelezettseg NUMERIC(15, 2),
    ek_x_1_halasztott_adokulonbozet NUMERIC(15, 2),
    ek_d_adozott_eredmeny NUMERIC(15, 2)
);